# POST https://connectbackend.llp.trizenventures.com/signin 
# Content-Type: application/json

# {
#     "email" : "kunaal10@gmail.com",
#     "password" : "Ku"
# }

GET https://connectbackend.llp.trizenventures.com/get-upload-url